[toolchain]
anchor_version = "0.32.0"

[features]
resolution = false
skip-lint = false

[programs.localnet]
oracle_bet = "BFv69p4dBZtPvDcUUnVBhiCCgAFVq5gpEWspnfmKxRKY"

[programs.devnet]
oracle_bet = "BFv69p4dBZtPvDcUUnVBhiCCgAFVq5gpEWspnfmKxRKY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "C:/Projects/MagickBlock/oracle_bet/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
